SmartDoctor.Web/Controllers/OutpatientController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using SmartDoctor.Data.ContextModels;
using SmartDoctor.Data.Enums;
using SmartDoctor.Data.JsonModels;
using SmartDoctor.Data.Models;
using SmartDoctor.Helper;
using SmartDoctor.Web.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartDoctor.Web.Controllers
{
    public class OutpatientController : Controller
    {
        private readonly IControllerRepository _controllerRepository;
        public OutpatientController(IControllerRepository controllerRepository)
        {
            _controllerRepository = controllerRepository;
        }

        public async Task<IActionResult> Index()
        {
            var medicalResponse = JsonConvert.DeserializeObject<MksResponse>(
              await RequestExecutor.ExecuteRequestAsync(
                  MicroservicesEnum.Medical, RequestUrl.GetOutpatients));
            if (!medicalResponse.Success)
                throw new Exception(medicalResponse.Data);
            var outpatients = JsonConvert.DeserializeObject<List<OutpatientModel>>(medicalResponse.Data);
            return View(outpatients);
        }

        public async Task<IActionResult> TakePatient()
        {
            var testingResponse = JsonConvert.DeserializeObject<MksResponse>(
              await RequestExecutor.ExecuteRequestAsync(
                  MicroservicesEnum.Testing, RequestUrl.GetPatientsWithNoReception));
            if (!testingResponse.Success)
                throw new Exception(testingResponse.Data);
            var ids = JsonConvert.DeserializeObject<long[]>(testingResponse.Data);
            var userResponse = JsonConvert.DeserializeObject<MksResponse>(
             await RequestExecutor.ExecuteRequestAsync(
                 MicroservicesEnum.User, RequestUrl.GetPatientsByIds, new Parameter[]{
                     new Parameter("ids", JsonConvert.SerializeObject(ids), ParameterType.RequestBody )
                 }));
            if (!userResponse.Success)
                throw new Exception(userResponse.Data);
            var outpatients = JsonConvert.DeserializeObject<List<PatientModel>>(userResponse.Data);
            ViewBag.Patients = outpatients.Select(x => x.Fio);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateCard()
        {
            var userId = _controllerRepository.GetUserId(User);
            var testingResponse = JsonConvert.DeserializeObject<MksResponse>(
               await RequestExecutor.ExecuteRequestAsync(
                   MicroservicesEnum.Medical, RequestUrl.CreateOutpatientCard, new Parameter[]{
                           new Parameter("userId", userId, ParameterType.RequestBody) }));
            if (!testingResponse.Success)
                throw new Exception(testingResponse.Data);
            return Json(new { Success = true, Message = "ok" });
        }

        [HttpGet]
        public async Task<IActionResult> PatientReception(PatientFioModel model)
        {
            var userResponse = JsonConvert.DeserializeObject<MksResponse>(await RequestExecutor.ExecuteRequestAsync(
                 MicroservicesEnum.User, RequestUrl.GetPatientByFio,
                     new Parameter[] {
                            new Parameter("fio", model.Fio, ParameterType.GetOrPost)
                     }));
            if (!userResponse.Success)
                throw new Exception(userResponse.Data);
            var patient = JsonConvert.DeserializeObject<PatientModel>(userResponse.Data);
            var testingResponse = JsonConvert.DeserializeObject<MksResponse>(
               await RequestExecutor.ExecuteRequestAsync(
                   MicroservicesEnum.Testing, RequestUrl.GetPreDiseaseId, new Parameter[]{
                           new Parameter("userId", long.Parse(patient.UserId), ParameterType.GetOrPost)
                       }));
            if (!testingResponse.Success)
                throw new Exception(testingResponse.Data);
            var diseaseId = JsonConvert.DeserializeObject<long>(testingResponse.Data);
            var medicalResponse = JsonConvert.DeserializeObject<MksResponse>(
               await RequestExecutor.ExecuteRequestAsync(
                   MicroservicesEnum.Medical, RequestUrl.GetDiseaseNameById, new Parameter[]{
                           new Parameter(
                               "diseaseId", diseaseId, ParameterType.GetOrPost)
                       }));
            if (!medicalResponse.Success)
                throw new Exception(medicalResponse.Data);

            var medicalResponse2 = JsonConvert.DeserializeObject<MksResponse>(
             await RequestExecutor.ExecuteRequestAsync(
                 MicroservicesEnum.Medical, RequestUrl.GetAllDiseases));
            if (!medicalResponse2.Success)
                throw new Exception(medicalResponse2.Data);
            var diseases = JsonConvert.DeserializeObject<List<string>>(medicalResponse2.Data);
            ViewBag.PreDiagnos = medicalResponse.Data;
            ViewBag.PatientId = patient.PatientId;
            ViewBag.Diseases = diseases;
            return View(patient);
        }

        [HttpPost]
        public async Task<IActionResult> AccessAnswer(long patientId)
        {
            try
            {
                var testingResponse = JsonConvert.DeserializeObject<MksResponse>(
                  await RequestExecutor.ExecuteRequestAsync(
                       MicroservicesEnum.Testing, RequestUrl.GetNotViewedAnswer, new Parameter[]
                       {
                            new Parameter("patientId", patientId, ParameterType.GetOrPost)
                       }));
                if (!testingResponse.Success)
                    throw new Exception(testingResponse.Data);
                var answerId = JsonConvert.DeserializeObject<long>(testingResponse.Data);
                var testingResponse2 = JsonConvert.DeserializeObject<MksResponse>(
                      await RequestExecutor.ExecuteRequestAsync(
                           MicroservicesEnum.Testing, RequestUrl.IncludeTestToCalculations, new Parameter[]
                           {
                                 new Parameter("id", answerId, ParameterType.RequestBody)
                           }));
                if (!testingResponse2.Success)
                    throw new Exception(testingResponse2.Data);
                var diseaseId = JsonConvert.DeserializeObject<long>(testingResponse2.Data);
                //update outpatient
                var doctorId = _controllerRepository.GetUserId(User);
                var medicalResponse = JsonConvert.DeserializeObject<MksResponse>(
                    await RequestExecutor.ExecuteRequestAsync(
                        MicroservicesEnum.Medical, RequestUrl.GetOutpatientByPatientAndDoctorId, new Parameter[]{
                               new Parameter(
                                   "model", JsonConvert.SerializeObject(new DoctorPatientModel
                                   {
                                       DoctorId = doctorId,
                                       PatientId = patientId,
                                       DiseaseId = diseaseId
                                   }), ParameterType.RequestBody)
                          }));
                if (!medicalResponse.Success)
                    throw new Exception(medicalResponse.Data);
                var outpatient = JsonConvert.DeserializeObject<OutpatientModel>(medicalResponse.Data);
                var medicalResponse2 = JsonConvert.DeserializeObject<MksResponse>(
                   await RequestExecutor.ExecuteRequestAsync(
                       MicroservicesEnum.Medical, RequestUrl.ChangeCardStatus, new Parameter[]{
                               new Parameter("model", JsonConvert.SerializeObject(new CardStatusModel
                               {
                                   CardId = outpatient.OutpatientCardId,
                                   Status = (byte) OutpatientStatuses.DoctorVisit
                               }), ParameterType.RequestBody)}));
                if (!medicalResponse2.Success)
                    throw new Exception(medicalResponse2.Data);
                return Json(new
                {
                    Success = true,
                    Data = outpatient.OutpatientCardId
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    Message  = ex.Message.ToString()
                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> DiscardAnswer(long patientId)
        {
            try
            {
                var testingResponse = JsonConvert.DeserializeObject<MksResponse>(
                      await RequestExecutor.ExecuteRequestAsync(
                           MicroservicesEnum.User, RequestUrl.GetUserByPatientId, new Parameter[]
                           {
                               new Parameter("patientId", patientId, ParameterType.GetOrPost)
                           }));
                if (!testingResponse.Success)
                    throw new Exception(testingResponse.Data);
                var user = JsonConvert.DeserializeObject<Users>(testingResponse.Data);
                var testingResponse2 = JsonConvert.DeserializeObject<MksResponse>(
                  await RequestExecutor.ExecuteRequestAsync(
                       MicroservicesEnum.Testing, RequestUrl.RemoveAnswer, new Parameter[]
                       {
                            new Parameter("userId", user.UserId, ParameterType.RequestBody)
                       }));
                if (!testingResponse2.Success)
                    throw new Exception(testingResponse2.Data);
                //update outpatient

SmartDoctor.Web/Views/Outpatient/Index.cshtml
@{
    ViewData["Title"] = "Outpatient list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using SmartDoctor.Data.JsonModels;
@using SmartDoctor.Data.Enums;
@model IEnumerable<OutpatientModel>

<h2>List of outpatient cards.</h2>

<hr />
<div id="outpatient-list">
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Patient FIO</th>
            <th>Disease</th>
            <th>Created date</th>
            <th>Status</th>
            <th>Description</th>
        </tr>
        @foreach (var card in Model)
        {
        <tr>
            <td>
                <input class="text" type="text" hidden="hidden" style="width:170px;" id="idTextBox" value="@card.OutpatientCardId" />
                <label style="height:33px;" id="patientFioTextBox">@card.Patient.Fio</label>
            </td>
            <td>
                <label style="height:33px;" id="diseaseTextBox">@card.Disease</label>
            </td>
            <td>
                <label style="height:33px;" id="createdDateTextBox">@card.CreatedDate</label>
            </td>
            <td>
                @{
                    var listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "Card creating",
                        Value = ((int)OutpatientStatuses.OutpatientCardCreating).ToString()
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Doctor waiting",
                        Value = ((int)OutpatientStatuses.DoctorWaiting).ToString()
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Doctor visit",
                        Value = ((int)OutpatientStatuses.DoctorVisit).ToString()
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Data updating",
                        Value = ((int)OutpatientStatuses.DataUpdating).ToString()
                    });
                    listItems.First(x => x.Value == ((int)card.Status).ToString()).Selected = true;
                }
                @Html.DropDownList("StatusDDL", listItems, null, new { @id = "statusDDL", @class = "form-control", @onchange = "OnChangeStatusDDL(this.value, this.id)" })
            </td>
            <td>
                <label style="height:33px;" id="descriptionTextBox">@card.Description</label>
            </td>
        </tr>
        }
    </table>
</div>
<script type="text/javascript">

    var UIelements = ["idTextBox", "statusDDL"];
    
    function getSecondPart(str) {
        return str.split('_')[1];
    }

    $(document).ready(function () {
        for (i = 0; i < UIelements.length; i++) {
            var elementsById = document.querySelectorAll('[id=' + UIelements[i] + ']');
            for (j = 0; j < elementsById.length; j++) {
                var newID = UIelements[i] + "_" + j;
                $(elementsById[j]).attr('id', newID);
            }
        }
    })

    
    function OnChangeStatusDDL(val, id) {
        var cardId = $("#idTextBox_" + getSecondPart(id)).val();
        var urlPath = '@Url.Action("ChangeStatus", "Outpatient")';
        $.ajax({
            type: "POST",
            data:
            {
                "CardId": cardId,
                "Status": val
            },
            url: urlPath,
            success: function () {
                alert("Status updated");
                location.reload();
            },
            error: function () {
                alert("error");
            }
        });
    }

</script>

SmartDoctor.Web/Views/Outpatient/PatientReception.cshtml
@using SmartDoctor.Data.JsonModels;


<h2>Patient reception</h2>

<center>
    <br />
    <hr />
    <center>
        <h3>
            <label id="prediagnLabel">
                Patient preliminary diagnosis is @ViewBag.PreDiagnos.
            </label>
        </h3>
        <br />
        <br />
        <button class="btn-success" style="width: 150px; height: 30px;" id="accessButton">Approve</button>
        <br />
        <br />
        <button class="btn-danger" style="width: 150px; height: 30px;" id="cancelButton">Discard</button>
        <br />
        <br />

        @Html.DropDownList("diseasesDDL",
            new SelectList(ViewBag.Diseases),
            "Select disease",
            new { @id = "diseasesDDL", @style = "width: 278px; height: 30px;", @class = "form-control" })
        <br />

        <label>Description</label>
        <br />
        <input class="text-success" style="width:400px; height: 100px;" id="description" type="text" />
        <br />
        <br />
        <button class="btn-success" style="width: 150px; height: 30px;" id="completeBtn">Complete inspection</button>
        <br />

    </center>

</center>


<script>
    var patientFio = '@ViewBag.PatientFio';
    var cardId = -1;

    $("#completeBtn").click(function () {
        var description = $("#description").val();
        var disease = $("#diseasesDDL").val();
        var urlPath = '@Url.Action("UpdateDescription", "Outpatient")';
        $.ajax({
            type: "POST",
            data:
            {
                "CardId": cardId,
                "Description": description,
                "Disease": disease
            },
            url: urlPath,
            success: function () {
                alert("Description updated");
                window.location.href = '@Url.Action("Index", "Outpatient")';
            },
            error: function () {
                alert("error");
            }
        });
    });

    $("#accessButton").click(function () {
       var urlPath = '@Url.Action("AccessAnswer", "Outpatient")';
       $.ajax({
            type: "POST",
            data:
            {
                "patientId": '@ViewBag.PatientId'
            },
            url: urlPath,
           success: function (data) {
               if (data.success == true) {
                   alert("Answer approved!");
                   $("#accessButton").hide();
                   $("#cancelButton").hide(); 
                   $("#prediagnLabel").hide();
                   $("#diseasesDDL").hide();
                   cardId = data.data;
               }
               else
                   alert("error! " + data.message);
            },
            error: function () {
                alert("error");
            }
        });
    });


    $("#cancelButton").click(function () {
        var urlPath = '@Url.Action("DiscardAnswer", "Outpatient")';
       $.ajax({
            type: "POST",
           data:
           {
              "patientId": '@ViewBag.PatientId'
                },
            url: urlPath,
           success: function (data) {
               if (data.success == true) {
                   alert("Answer removed!");
                   $("#accessButton").hide();
                   $("#cancelButton").hide();
                   $("#prediagnLabel").hide();
                   cardId = data.data;
               }
               else {
                   alert("error!" + data.message);

               }
            },
            error: function () {
                alert("error");
            }
        });
    });

 
</script>

SmartDoctor.Web/Views/Outpatient/TakePatient.cshtml
@{
    ViewData["Title"] = "Take a patient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Choose a patient</h2>
<br />
<center>
    @Html.DropDownList("patientDDL",
        new SelectList(ViewBag.Patients),
        "Patient",
        new { @id = "patientDDL", @style = "width: 278px; height: 30px;", @class = "form-control" })
    <br />
    <button style="width: 150px; height: 30px;" class="btn-success" id="takeBtn" onclick="onClickTakeBtn()">Take!</button>
</center>
<script type="text/javascript">
    
    function onClickTakeBtn() {
        var patient = $("#patientDDL").val();
        window.location.href = '@Url.Action("PatientReception", "Outpatient")' + '/?fio=' + patient;
    }
</script>